create table if not exists public.team_rating_snapshots (
  id bigint generated by default as identity primary key,

  season_id bigint not null
    references public.seasons(id) on delete cascade,

  team_id bigint not null
    references public.teams(id) on delete cascade,

  through_week integer not null
    check (through_week >= 0),

  season_type text not null default 'regular',

  source_team_name text,

  sp_rating numeric,
  sp_ranking integer,
  sp_second_order_wins numeric,
  sp_sos numeric,

  srs_rating numeric,
  srs_ranking integer,

  elo integer,

  fpi numeric,

  core_overall numeric,
  core_offense numeric,
  core_defense numeric,
  core_offense_plays integer,
  core_defense_plays integer,
  core_through_week integer,
  core_through_season_type text,
  core_model_version text,

  source_data jsonb not null default '{}'::jsonb,

  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now(),

  unique (
    season_id,
    team_id,
    through_week,
    season_type
  )
);

create index if not exists team_rating_snapshots_season_week_idx
  on public.team_rating_snapshots (
    season_id,
    through_week,
    season_type
  );

create index if not exists team_rating_snapshots_team_idx
  on public.team_rating_snapshots (
    team_id,
    season_id,
    through_week desc
  );

alter table public.team_rating_snapshots
enable row level security;

revoke all
on table public.team_rating_snapshots
from public, anon, authenticated;

grant select, insert, update, delete
on table public.team_rating_snapshots
to service_role;

grant usage, select
on sequence public.team_rating_snapshots_id_seq
to service_role;
