'use client';
import {useEffect,useMemo,useState} from 'react';import {createClient} from '@supabase/supabase-js';import {TeamName} from '../team-name';
export default function WaiversClient(){
 const supabase=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY),[]);
 const [data,setData]=useState(null),[msg,setMsg]=useState(''),[selected,setSelected]=useState(null),[drop,setDrop]=useState('');
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token}
 async function load(){const t=await token();if(!t){setMsg('Sign in through the Account tab to use waivers.');return}const r=await fetch('/api/waivers',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const j=await r.json();setData(j);if(!r.ok)setMsg(j.error)}
 useEffect(()=>{load()},[]);
 async function claim(){const t=await token();const r=await fetch('/api/waivers',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({add_team_id:selected.team_id,drop_team_id:Number(drop)})});const j=await r.json();if(!r.ok)return setMsg(j.error);setMsg('Claim submitted.');setSelected(null);setDrop('');load()}
 async function cancel(id){const t=await token();await fetch('/api/waivers',{method:'DELETE',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({id})});load()}
 if(!data)return <section className="section"><div className="card">{msg||'Loading waivers…'}</div></section>;
 const byId=new Map([...data.available,...data.roster].map(t=>[Number(t.team_id),t]));
 return <><section className="section"><div className="card waiverStatus"><b>Next waiver period: {data.period.key}</b><span>{data.period.deadline?new Date(data.period.deadline).toLocaleString([],{dateStyle:'medium',timeStyle:'short'}):'Waivers closed'}</span><small>Claims process only at the end of our custom fantasy week. Teams with 5+ wins are ineligible.</small></div></section>
 <section className="section"><div className="sectionTitle"><h2>My Claims</h2><span className="muted">Processed in the order shown</span></div>{data.claims.length?data.claims.map(c=><div className="card waiverClaim" key={c.id}><b>#{c.priority}</b><span>Add <TeamName school={byId.get(Number(c.add_team_id))?.school||'Team'} size="sm"/></span><span>Drop <TeamName school={byId.get(Number(c.drop_team_id))?.school||'Team'} size="sm"/></span><button className="button secondary" onClick={()=>cancel(c.id)}>Cancel</button></div>):<div className="card muted">No claims submitted yet.</div>}</section>
 <section className="section"><div className="sectionTitle"><h2>Available Teams</h2><span className="muted">{data.available.length} eligible</span></div><div className="waiverGrid">{data.available.map(t=><button className="card waiverTeam" key={t.team_id} onClick={()=>{setSelected(t);setDrop('')}}><TeamName team={t}/><small>{t.conference_code} · {t.wins}-{t.losses} · {t.fantasy_points} fantasy pts</small></button>)}</div></section>
 {selected?<div className="waiverModal"><div className="card waiverDialog"><h2>Claim <TeamName team={selected}/></h2><p className="muted">Choose the team you would drop. Only legal drops are shown.</p><select value={drop} onChange={e=>setDrop(e.target.value)}><option value="">Choose drop…</option>{selected.eligible_drops.map(t=><option value={t.team_id} key={t.team_id}>{t.school} ({t.conference_code}{t.roster_slot==='FLEX'?' · Flex':''})</option>)}</select><div className="accountActions"><button className="button" disabled={!drop} onClick={claim}>Confirm Claim</button><button className="button secondary" onClick={()=>setSelected(null)}>Cancel</button></div></div></div>:null}{msg&&<div className="waiverToast">{msg}</div>}</>
}
