'use client';
import {useEffect,useMemo,useState} from 'react';import {createClient} from '@supabase/supabase-js';import {TeamName} from '../team-name';
export default function WaiversClient(){
 const supabase=useMemo(()=>createClient(process.env.NEXT_PUBLIC_SUPABASE_URL,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY),[]);
 const [data,setData]=useState(null),[msg,setMsg]=useState(''),[selected,setSelected]=useState(null),[drop,setDrop]=useState(''),[conference,setConference]=useState('ALL'),[sort,setSort]=useState('projection'),[moving,setMoving]=useState(null);
 async function token(){const {data}=await supabase.auth.getSession();return data.session?.access_token}
 async function load(){const t=await token();if(!t){setMsg('Sign in through Account to use waivers.');return}const r=await fetch('/api/waivers',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'}),j=await r.json();setData(j);if(!r.ok)setMsg(j.error)}
 useEffect(()=>{load()},[]);
 async function claim(){const t=await token();const r=await fetch('/api/waivers',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({add_team_id:selected.team_id,drop_team_id:Number(drop)})}),j=await r.json();if(!r.ok)return setMsg(j.error);setMsg('Claim submitted.');setSelected(null);setDrop('');load()}
 async function cancel(id){const t=await token();const r=await fetch('/api/waivers',{method:'DELETE',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({id})});const j=await r.json();if(!r.ok)setMsg(j.error);load()}
 async function move(id,direction){setMoving(id);const t=await token();const r=await fetch('/api/waivers',{method:'PATCH',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({id,direction})}),j=await r.json();if(!r.ok)setMsg(j.error);await load();setMoving(null)}
 if(!data)return <section className="section"><div className="card">{msg||'Loading waivers…'}</div></section>;
 const byId=new Map([...data.available,...data.roster].map(t=>[Number(t.team_id),t]));
 const conferences=[...new Set(data.available.map(t=>t.conference_code).filter(Boolean))].sort((a,b)=>a.localeCompare(b));
 const teams=data.available.filter(t=>conference==='ALL'||t.conference_code===conference).sort((a,b)=>{
   if(sort==='projection'){if(a.eligible!==b.eligible)return a.eligible?-1:1;return Number(b.season_projected_points??-999)-Number(a.season_projected_points??-999)||a.school.localeCompare(b.school)}
   if(sort==='points')return Number(b.fantasy_points||0)-Number(a.fantasy_points||0)||a.school.localeCompare(b.school);
   if(sort==='conference')return String(a.conference_code||'').localeCompare(String(b.conference_code||''))||a.school.localeCompare(b.school);
   return a.school.localeCompare(b.school);
 });
 const deadline=data.period.deadline?new Date(data.period.deadline):null;
 return <>
 <section className="section waiverStatusSection"><div className={`card waiverStatusCompact ${data.period.closed?'closed':''}`}><div><b>{data.period.closed?'WAIVERS CLOSED':`${data.period.key} · WAIVERS OPEN`}</b>{!data.period.closed&&<span>Runs {deadline.toLocaleString([],{month:'short',day:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'})}</span>}</div><div className="waiverEligibility"><small>ELIGIBILITY</small><b>4 wins or fewer</b></div></div></section>
 <section className="section waiverClaimsSection"><div className="sectionTitle"><div><h2>My Claims</h2><span className="muted waiverOrderNote">Processed in the order shown.</span></div></div>{data.claims.length?<div className="waiverClaimList">{data.claims.map((c,i)=><div className="card waiverClaimCompact" key={c.id}><b className="claimPriority">#{i+1}</b><div className="claimSwap"><span><small>Add</small><b><TeamName team={byId.get(Number(c.add_team_id))} school={byId.get(Number(c.add_team_id))?.school||'Team'} size="sm"/></b></span><span><small>Drop</small><b><TeamName team={byId.get(Number(c.drop_team_id))} school={byId.get(Number(c.drop_team_id))?.school||'Team'} size="sm"/></b></span></div><div className="claimActions"><button aria-label="Move claim up" title="Move up" disabled={i===0||moving===c.id} onClick={()=>move(c.id,'up')}>↑</button><button aria-label="Move claim down" title="Move down" disabled={i===data.claims.length-1||moving===c.id} onClick={()=>move(c.id,'down')}>↓</button><button className="claimCancel" onClick={()=>cancel(c.id)}>Cancel</button></div></div>)}</div>:<div className="card muted waiverEmpty">No claims submitted yet.</div>}</section>
 <section className="section"><div className="waiverAvailableHead"><div><h2>Available Teams</h2><span className="muted">{data.eligible_count} eligible</span></div><div className="waiverControls"><select aria-label="Filter by conference" value={conference} onChange={e=>setConference(e.target.value)}><option value="ALL">All Conferences</option>{conferences.map(c=><option key={c} value={c}>{c}</option>)}</select><select aria-label="Sort available teams" value={sort} onChange={e=>setSort(e.target.value)}><option value="projection">Projected Points</option><option value="points">Points</option><option value="alphabetical">Alphabetical</option><option value="conference">Conference</option></select></div></div>
 <div className="waiverGrid compactWaiverGrid">{teams.map(t=><button disabled={!t.eligible} className={`card waiverTeam compactWaiverTeam ${!t.eligible?'waiverIneligible':''}`} key={t.team_id} onClick={()=>{if(t.eligible){setSelected(t);setDrop('')}}}><span className="waiverTeamName"><TeamName team={t}/></span><span className="waiverTeamStats"><small>{t.conference_code}</small><small>{t.wins}-{t.losses}</small><small><b>{t.fantasy_points}</b> Pts</small><small className={t.eligible?'':'ineligibleLabel'}>{t.eligible?`${t.season_projected_points==null?'—':Number(t.season_projected_points).toFixed(1)} Proj`:'INELIGIBLE'}</small></span></button>)}</div></section>
 {selected?<div className="waiverModal"><div className="card waiverDialog"><h2>Claim <TeamName team={selected}/></h2><p className="muted">Choose the team you would drop. Only legal drops are shown.</p><select value={drop} onChange={e=>setDrop(e.target.value)}><option value="">Choose drop…</option>{selected.eligible_drops.map(t=><option value={t.team_id} key={t.team_id}>{t.school} ({t.conference_code})</option>)}</select><div className="accountActions"><button className="button" disabled={!drop} onClick={claim}>Confirm Claim</button><button className="button secondary" onClick={()=>setSelected(null)}>Cancel</button></div></div></div>:null}{msg&&<div className="waiverToast">{msg}</div>}</>;
}