create table public.owner_projection_snapshots (
  id bigint generated by default as identity primary key,
  run_id bigint not null references public.projection_runs(id) on delete cascade,
  season_id bigint not null references public.seasons(id) on delete cascade,
  owner_id bigint not null references public.owners(id) on delete cascade,
  projected_points numeric(8,3) not null default 0,
  projected_rank integer not null,
  snapshot_at timestamptz not null,
  created_at timestamptz not null default now(),
  constraint owner_projection_snapshots_run_owner_key unique (run_id, owner_id),
  constraint owner_projection_snapshots_rank_check check (projected_rank > 0)
);

create index owner_projection_snapshots_season_snapshot_idx
  on public.owner_projection_snapshots (season_id, snapshot_at);

alter table public.owner_projection_snapshots enable row level security;

revoke all on table public.owner_projection_snapshots from anon, authenticated;
grant select on table public.owner_projection_snapshots to anon, authenticated;
grant all on table public.owner_projection_snapshots to service_role;
grant usage, select on sequence public.owner_projection_snapshots_id_seq to service_role;

create policy "Public can read owner projection snapshots"
  on public.owner_projection_snapshots
  for select
  to anon, authenticated
  using (true);

with totals as (
  select
    pr.id as run_id,
    pr.season_id,
    pr.snapshot_at,
    o.id as owner_id,
    o.draft_slot,
    sum(tps.projected_points)::numeric(8,3) as projected_points
  from public.projection_runs pr
  join public.owners o
    on o.season_id = pr.season_id
  join public.team_ownership_history toh
    on toh.season_id = pr.season_id
   and toh.owner_id = o.id
   and toh.acquired_at <= pr.snapshot_at
   and (toh.released_at is null or toh.released_at > pr.snapshot_at)
  join public.team_projection_snapshots tps
    on tps.run_id = pr.id
   and tps.team_id = toh.team_id
  where pr.publishable
  group by pr.id, pr.season_id, pr.snapshot_at, o.id, o.draft_slot
),
ranked as (
  select
    run_id,
    season_id,
    owner_id,
    projected_points,
    rank() over (
      partition by run_id
      order by projected_points desc
    )::integer as projected_rank,
    snapshot_at
  from totals
)
insert into public.owner_projection_snapshots (
  run_id,
  season_id,
  owner_id,
  projected_points,
  projected_rank,
  snapshot_at
)
select
  run_id,
  season_id,
  owner_id,
  projected_points,
  projected_rank,
  snapshot_at
from ranked;
