create table if not exists public.waiver_processing_runs (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  waiver_period_key text not null,
  status text not null check (status in ('running', 'completed', 'failed')),
  trigger_source text not null check (trigger_source in ('cron', 'manual')),
  attempt_count integer not null default 1 check (attempt_count > 0),
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  result jsonb not null default '{}'::jsonb,
  last_error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (season_id, waiver_period_key)
);

alter table public.waiver_processing_runs enable row level security;
revoke all on table public.waiver_processing_runs from anon, authenticated;
grant all on table public.waiver_processing_runs to service_role;
grant usage, select on sequence public.waiver_processing_runs_id_seq to service_role;

create unique index if not exists waiver_transactions_claim_id_key
  on public.waiver_transactions (claim_id)
  where claim_id is not null;

create or replace function public.execute_waiver_transaction(
  p_season_id bigint,
  p_period text,
  p_owner_id bigint,
  p_add_team_id bigint,
  p_drop_team_id bigint,
  p_claim_id bigint,
  p_round integer,
  p_order integer,
  p_competing bigint[],
  p_effective_at timestamptz default now()
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_transaction_id bigint;
  v_roster_slot_id bigint;
  v_claim public.waiver_claims%rowtype;
begin
  select id into v_transaction_id
  from public.waiver_transactions
  where claim_id = p_claim_id;

  if found then
    return v_transaction_id;
  end if;

  select * into v_claim
  from public.waiver_claims
  where id = p_claim_id
  for update;

  if not found
     or v_claim.status <> 'pending'
     or v_claim.season_id <> p_season_id
     or v_claim.waiver_period_key <> p_period
     or v_claim.owner_id <> p_owner_id
     or v_claim.add_team_id <> p_add_team_id
     or v_claim.drop_team_id <> p_drop_team_id then
    raise exception 'Claim is not pending or does not match the transaction';
  end if;

  perform id
  from public.roster_entries
  where season_id = p_season_id
    and team_id = p_add_team_id
  for update;

  if found then
    raise exception 'Add team is already owned';
  end if;

  select roster_slot_id into v_roster_slot_id
  from public.roster_entries
  where season_id = p_season_id
    and owner_id = p_owner_id
    and team_id = p_drop_team_id
  for update;

  if not found then
    raise exception 'Drop team is not on owner roster';
  end if;

  insert into public.waiver_transactions (
    season_id,
    waiver_period_key,
    owner_id,
    add_team_id,
    drop_team_id,
    claim_id,
    waiver_round,
    waiver_order,
    effective_at,
    competing_claim_owner_ids
  ) values (
    p_season_id,
    p_period,
    p_owner_id,
    p_add_team_id,
    p_drop_team_id,
    p_claim_id,
    p_round,
    p_order,
    p_effective_at,
    coalesce(p_competing, '{}'::bigint[])
  )
  returning id into v_transaction_id;

  update public.team_ownership_history
  set released_at = p_effective_at,
      transaction_id = v_transaction_id
  where season_id = p_season_id
    and owner_id = p_owner_id
    and team_id = p_drop_team_id
    and released_at is null;

  update public.roster_entries
  set team_id = p_add_team_id,
      draft_pick = null
  where season_id = p_season_id
    and owner_id = p_owner_id
    and roster_slot_id = v_roster_slot_id;

  insert into public.team_ownership_history (
    season_id,
    owner_id,
    team_id,
    roster_slot_id,
    acquired_at,
    acquisition_type,
    transaction_id
  ) values (
    p_season_id,
    p_owner_id,
    p_add_team_id,
    v_roster_slot_id,
    p_effective_at,
    'waiver',
    v_transaction_id
  );

  update public.waiver_claims
  set status = 'successful',
      failure_reason = null,
      processed_at = p_effective_at,
      updated_at = p_effective_at
  where id = p_claim_id;

  return v_transaction_id;
end;
$$;

revoke all on function public.execute_waiver_transaction(
  bigint,
  text,
  bigint,
  bigint,
  bigint,
  bigint,
  integer,
  integer,
  bigint[],
  timestamptz
) from public, anon, authenticated;

grant execute on function public.execute_waiver_transaction(
  bigint,
  text,
  bigint,
  bigint,
  bigint,
  bigint,
  integer,
  integer,
  bigint[],
  timestamptz
) to service_role;

create or replace function public.execute_waiver_period(
  p_season_id bigint,
  p_period text,
  p_steps jsonb,
  p_trigger_source text,
  p_effective_at timestamptz default now()
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_existing_result jsonb;
  v_pending_count integer;
  v_step jsonb;
  v_claim public.waiver_claims%rowtype;
  v_claim_ids bigint[] := '{}'::bigint[];
  v_claim_id bigint;
  v_status text;
  v_transaction_id bigint;
  v_roster_slot_id bigint;
  v_transactions jsonb := '[]'::jsonb;
  v_unsuccessful integer := 0;
  v_result jsonb;
begin
  if p_trigger_source not in ('cron', 'manual') then
    raise exception 'Invalid waiver trigger source';
  end if;

  if jsonb_typeof(p_steps) <> 'array' then
    raise exception 'Waiver plan must be a JSON array';
  end if;

  perform pg_catalog.pg_advisory_xact_lock(
    pg_catalog.hashtextextended(
      p_season_id::text || ':' || p_period,
      0
    )
  );

  select result into v_existing_result
  from public.waiver_processing_runs
  where season_id = p_season_id
    and waiver_period_key = p_period
    and status = 'completed';

  if found then
    return v_existing_result ||
      jsonb_build_object(
        'already_completed',
        true
      );
  end if;

  insert into public.waiver_processing_runs (
    season_id,
    waiver_period_key,
    status,
    trigger_source,
    attempt_count,
    started_at,
    completed_at,
    result,
    last_error,
    updated_at
  ) values (
    p_season_id,
    p_period,
    'running',
    p_trigger_source,
    1,
    now(),
    null,
    '{}'::jsonb,
    null,
    now()
  )
  on conflict (
    season_id,
    waiver_period_key
  ) do update
  set status = 'running',
      trigger_source = excluded.trigger_source,
      attempt_count =
        public.waiver_processing_runs.attempt_count + 1,
      started_at = now(),
      completed_at = null,
      last_error = null,
      updated_at = now();

  select count(*) into v_pending_count
  from public.waiver_claims
  where season_id = p_season_id
    and waiver_period_key = p_period
    and status = 'pending';

  if jsonb_array_length(p_steps) <> v_pending_count then
    raise exception
      'Waiver plan does not cover every pending claim';
  end if;

  for v_step in
    select value
    from jsonb_array_elements(p_steps)
  loop
    v_claim_id :=
      (v_step ->> 'claim_id')::bigint;

    v_status :=
      v_step ->> 'status';

    if v_claim_id = any(v_claim_ids) then
      raise exception
        'Waiver plan contains a duplicate claim';
    end if;

    v_claim_ids :=
      array_append(
        v_claim_ids,
        v_claim_id
      );

    select * into v_claim
    from public.waiver_claims
    where id = v_claim_id
      and season_id = p_season_id
      and waiver_period_key = p_period
      and status = 'pending'
    for update;

    if not found then
      raise exception
        'Waiver claim is missing or is no longer pending';
    end if;

    if v_status = 'successful' then
      if
        v_claim.owner_id <>
          (v_step ->> 'owner_id')::bigint
        or v_claim.add_team_id <>
          (v_step ->> 'add_team_id')::bigint
        or v_claim.drop_team_id <>
          (v_step ->> 'drop_team_id')::bigint
      then
        raise exception
          'Waiver plan does not match claim';
      end if;

      v_transaction_id :=
        public.execute_waiver_transaction(
          p_season_id,
          p_period,
          v_claim.owner_id,
          v_claim.add_team_id,
          v_claim.drop_team_id,
          v_claim.id,
          (v_step ->> 'round')::integer,
          (v_step ->> 'waiver_order')::integer,
          coalesce(
            array(
              select value::bigint
              from jsonb_array_elements_text(
                coalesce(
                  v_step -> 'competing_owner_ids',
                  '[]'::jsonb
                )
              )
            ),
            '{}'::bigint[]
          ),
          p_effective_at
        );

      v_transactions :=
        v_transactions ||
        jsonb_build_array(
          jsonb_build_object(
            'transaction_id',
            v_transaction_id,
            'claim_id',
            v_claim.id,
            'round',
            (v_step ->> 'round')::integer,
            'owner',
            v_step ->> 'owner_name',
            'add',
            v_step ->> 'add_team_name',
            'drop',
            v_step ->> 'drop_team_name'
          )
        );

    elsif v_status in (
      'lost_to_priority',
      'invalid'
    ) then

      update public.waiver_claims
      set status = v_status,
          failure_reason =
            coalesce(
              v_step ->> 'reason',
              'Claim was unsuccessful'
            ),
          processed_at = p_effective_at,
          updated_at = p_effective_at
      where id = v_claim.id;

      v_unsuccessful :=
        v_unsuccessful + 1;

    else
      raise exception
        'Invalid waiver plan status';
    end if;
  end loop;

  if exists (
    select 1
    from public.waiver_claims
    where season_id = p_season_id
      and waiver_period_key = p_period
      and status = 'pending'
  ) then
    raise exception
      'Pending claims remain after waiver processing';
  end if;

  v_result :=
    jsonb_build_object(
      'ok',
      true,
      'period',
      p_period,
      'effective_at',
      p_effective_at,
      'transactions',
      v_transactions,
      'successful',
      jsonb_array_length(v_transactions),
      'unsuccessful',
      v_unsuccessful,
      'already_completed',
      false
    );

  update public.waiver_processing_runs
  set status = 'completed',
      completed_at = now(),
      result = v_result,
      last_error = null,
      updated_at = now()
  where season_id = p_season_id
    and waiver_period_key = p_period;

  return v_result;
end;
$$;

revoke all on function public.execute_waiver_period(
  bigint,
  text,
  jsonb,
  text,
  timestamptz
) from public, anon, authenticated;

grant execute on function public.execute_waiver_period(
  bigint,
  text,
  jsonb,
  text,
  timestamptz
) to service_role;

create or replace function public.record_waiver_processing_failure(
  p_season_id bigint,
  p_period text,
  p_trigger_source text,
  p_error text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_trigger_source not in ('cron', 'manual') then
    raise exception
      'Invalid waiver trigger source';
  end if;

  insert into public.waiver_processing_runs (
    season_id,
    waiver_period_key,
    status,
    trigger_source,
    attempt_count,
    started_at,
    completed_at,
    result,
    last_error,
    updated_at
  ) values (
    p_season_id,
    p_period,
    'failed',
    p_trigger_source,
    1,
    now(),
    now(),
    '{}'::jsonb,
    left(p_error, 2000),
    now()
  )
  on conflict (
    season_id,
    waiver_period_key
  ) do update
  set status =
      case
        when
          public.waiver_processing_runs.status =
          'completed'
        then 'completed'
        else 'failed'
      end,

      trigger_source =
        excluded.trigger_source,

      attempt_count =
        case
          when
            public.waiver_processing_runs.status =
            'completed'
          then
            public.waiver_processing_runs.attempt_count
          else
            public.waiver_processing_runs.attempt_count + 1
        end,

      completed_at =
        case
          when
            public.waiver_processing_runs.status =
            'completed'
          then
            public.waiver_processing_runs.completed_at
          else
            now()
        end,

      last_error =
        case
          when
            public.waiver_processing_runs.status =
            'completed'
          then
            public.waiver_processing_runs.last_error
          else
            excluded.last_error
        end,

      updated_at = now();
end;
$$;

revoke all on function public.record_waiver_processing_failure(
  bigint,
  text,
  text,
  text
) from public, anon, authenticated;

grant execute on function public.record_waiver_processing_failure(
  bigint,
  text,
  text,
  text
) to service_role;
