create table if not exists public.preseason_win_totals (
  id bigint generated by default as identity primary key,
  season_id bigint not null references public.seasons(id) on delete cascade,
  team_id bigint not null references public.teams(id) on delete cascade,
  win_total numeric(5,2) not null,
  over_odds integer,
  under_odds integer,
  source text not null,
  captured_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique (season_id, team_id)
);

create index if not exists preseason_win_totals_season_id_idx
  on public.preseason_win_totals (season_id);

alter table public.preseason_win_totals enable row level security;

revoke all on table public.preseason_win_totals
from public, anon, authenticated;

grant select, insert, update, delete
on table public.preseason_win_totals
to service_role;

grant usage, select
on sequence public.preseason_win_totals_id_seq
to service_role;
