BEGIN;

CREATE TABLE IF NOT EXISTS public.admin_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_hash text NOT NULL,
  succeeded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS admin_login_attempts_requester_created_idx
  ON public.admin_login_attempts (requester_hash, created_at DESC);

ALTER TABLE public.admin_login_attempts ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.admin_login_attempts
FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.admin_login_attempts
TO service_role;


ALTER TABLE public.admin_audit_log ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integration_secrets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.integration_sync_state ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.admin_audit_log
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON TABLE public.integration_secrets
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON TABLE public.integration_sync_state
FROM PUBLIC, anon, authenticated;

GRANT ALL ON TABLE public.admin_audit_log TO service_role;
GRANT ALL ON TABLE public.integration_secrets TO service_role;
GRANT ALL ON TABLE public.integration_sync_state TO service_role;


ALTER TABLE public.team_aliases ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.weekly_snapshot_games ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS public_read_team_aliases
ON public.team_aliases;

CREATE POLICY public_read_team_aliases
ON public.team_aliases
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS public_read_weekly_snapshots
ON public.weekly_snapshots;

CREATE POLICY public_read_weekly_snapshots
ON public.weekly_snapshots
FOR SELECT
TO anon, authenticated
USING (true);

DROP POLICY IF EXISTS public_read_weekly_snapshot_games
ON public.weekly_snapshot_games;

CREATE POLICY public_read_weekly_snapshot_games
ON public.weekly_snapshot_games
FOR SELECT
TO anon, authenticated
USING (true);

REVOKE ALL ON TABLE public.team_aliases
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON TABLE public.weekly_snapshots
FROM PUBLIC, anon, authenticated;

REVOKE ALL ON TABLE public.weekly_snapshot_games
FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.team_aliases
TO anon, authenticated;

GRANT SELECT ON TABLE public.weekly_snapshots
TO anon, authenticated;

GRANT SELECT ON TABLE public.weekly_snapshot_games
TO anon, authenticated;

GRANT ALL ON TABLE public.team_aliases TO service_role;
GRANT ALL ON TABLE public.weekly_snapshots TO service_role;
GRANT ALL ON TABLE public.weekly_snapshot_games TO service_role;


ALTER TABLE public.user_profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS profiles_public_read
ON public.user_profiles;

DROP POLICY IF EXISTS profiles_read_self
ON public.user_profiles;

CREATE POLICY profiles_read_self
ON public.user_profiles
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS profiles_insert_self
ON public.user_profiles;

CREATE POLICY profiles_insert_self
ON public.user_profiles
FOR INSERT
TO authenticated
WITH CHECK (
  auth.uid() = user_id
  AND owner_id IS NULL
  AND role = 'owner'::text
);

DROP POLICY IF EXISTS profiles_update_self_username
ON public.user_profiles;

CREATE POLICY profiles_update_self_username
ON public.user_profiles
FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (
  auth.uid() = user_id
  AND NOT (
    owner_id IS DISTINCT FROM (
      SELECT p.owner_id
      FROM public.user_profiles p
      WHERE p.user_id = auth.uid()
    )
  )
  AND NOT (
    role IS DISTINCT FROM (
      SELECT p.role
      FROM public.user_profiles p
      WHERE p.user_id = auth.uid()
    )
  )
);

REVOKE ALL ON TABLE public.user_profiles
FROM PUBLIC, anon, authenticated;

GRANT SELECT, INSERT, UPDATE
ON TABLE public.user_profiles
TO authenticated;

GRANT ALL ON TABLE public.user_profiles
TO service_role;


ALTER TABLE public.waiver_claims ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS owners_read_own_waiver_claims
ON public.waiver_claims;

CREATE POLICY owners_read_own_waiver_claims
ON public.waiver_claims
FOR SELECT
TO authenticated
USING (
  owner_id = (
    SELECT up.owner_id
    FROM public.user_profiles up
    WHERE up.user_id = auth.uid()
  )
  OR (
    SELECT up.role
    FROM public.user_profiles up
    WHERE up.user_id = auth.uid()
  ) = 'commissioner'::text
);

REVOKE ALL ON TABLE public.waiver_claims
FROM PUBLIC, anon, authenticated;

GRANT SELECT ON TABLE public.waiver_claims
TO authenticated;

GRANT ALL ON TABLE public.waiver_claims
TO service_role;


ALTER VIEW public.owner_head_to_head_games
SET (security_invoker = true);

ALTER VIEW public.owner_head_to_head_records
SET (security_invoker = true);

ALTER VIEW public.team_projection_history
SET (security_invoker = true);

ALTER VIEW public.ownership_game_ledger
SET (security_invoker = true);

ALTER VIEW public.ownership_owner_game_totals
SET (security_invoker = true);

ALTER VIEW public.ownership_scoring_event_ledger
SET (security_invoker = true);

ALTER VIEW public.ownership_owner_fantasy_totals
SET (security_invoker = true);

ALTER VIEW public.ownership_owner_full_totals
SET (security_invoker = true);

ALTER VIEW public.official_regular_standings
SET (security_invoker = true);

ALTER VIEW public.official_waiver_order
SET (security_invoker = true);

ALTER VIEW public.owner_final_tiebreakers
SET (security_invoker = true);

ALTER VIEW public.official_final_standings
SET (security_invoker = true);

ALTER VIEW public.owner_standings_with_movement
SET (security_invoker = true);

ALTER VIEW public.owner_weekly_record_stats
SET (security_invoker = true);

ALTER VIEW public.latest_team_projections
SET (security_invoker = true);

ALTER VIEW public.draft_history
SET (security_invoker = true);

ALTER VIEW public.owner_projection_totals
SET (security_invoker = true);

ALTER VIEW public.waiver_transaction_history
SET (security_invoker = true);

ALTER VIEW public.owner_previous_teams
SET (security_invoker = true);


GRANT SELECT ON TABLE public.draft_history
TO anon, authenticated;

GRANT SELECT ON TABLE public.latest_team_projections
TO anon, authenticated;

GRANT SELECT ON TABLE public.owner_previous_teams
TO anon, authenticated;

GRANT SELECT ON TABLE public.owner_projection_totals
TO anon, authenticated;

GRANT SELECT ON TABLE public.owner_standings_with_movement
TO anon, authenticated;

GRANT SELECT ON TABLE public.ownership_scoring_event_ledger
TO anon, authenticated;

GRANT SELECT ON TABLE public.team_projection_history
TO anon, authenticated;

GRANT SELECT ON TABLE public.waiver_transaction_history
TO anon, authenticated;


ALTER FUNCTION public.handle_new_auth_user()
SET search_path = '';

ALTER FUNCTION public.touch_user_profile_updated_at()
SET search_path = '';

ALTER FUNCTION public.fantasy_week_key_2026(timestamp with time zone)
SET search_path = '';


DO $$
DECLARE
  fn regprocedure;
BEGIN
  FOR fn IN
    SELECT p.oid::regprocedure
    FROM pg_proc p
    JOIN pg_namespace n
      ON n.oid = p.pronamespace
    WHERE n.nspname = 'public'
      AND p.prosecdef = true
  LOOP
    EXECUTE format(
      'REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, anon, authenticated',
      fn
    );

    EXECUTE format(
      'GRANT EXECUTE ON FUNCTION %s TO service_role',
      fn
    );
  END LOOP;
END
$$;

COMMIT;
