create table if not exists public.automation_job_runs (
  id bigint generated by default as identity primary key,

  job_key text not null
    check (
      job_key ~ '^[a-z0-9_]+$'
    ),

  status text not null
    check (
      status in (
        'running',
        'succeeded',
        'failed',
        'skipped'
      )
    ),

  trigger_source text not null
    check (
      trigger_source in (
        'cron',
        'manual'
      )
    ),

  started_at timestamptz not null
    default now(),

  finished_at timestamptz,

  duration_ms integer
    check (
      duration_ms is null
      or duration_ms >= 0
    ),

  records_updated integer
    check (
      records_updated is null
      or records_updated >= 0
    ),

  details jsonb not null
    default '{}'::jsonb
    check (
      jsonb_typeof(details) = 'object'
    ),

  error_message text,

  created_at timestamptz not null
    default now(),

  check (
    (
      status = 'running'
      and finished_at is null
    )
    or
    (
      status <> 'running'
      and finished_at is not null
    )
  )
);

create index if not exists
  automation_job_runs_job_started_idx
on public.automation_job_runs (
  job_key,
  started_at desc
);

create index if not exists
  automation_job_runs_started_idx
on public.automation_job_runs (
  started_at desc
);

create index if not exists
  automation_job_runs_failed_idx
on public.automation_job_runs (
  started_at desc
)
where status = 'failed';

alter table public.automation_job_runs
  enable row level security;

revoke all
on table public.automation_job_runs
from public, anon, authenticated;

grant select, insert, update
on table public.automation_job_runs
to service_role;

grant usage, select
on sequence public.automation_job_runs_id_seq
to service_role;
