create table if not exists public.weekly_recaps (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.seasons(id)
    on delete cascade,
  week_key text not null,
  status text not null default 'draft'
    check (status in ('draft', 'published')),
  headline text not null default 'Weekly Recap',
  recap_text text not null default '',
  recap_data jsonb not null default '{}'::jsonb
    check (jsonb_typeof(recap_data) = 'object'),
  source_finalized_at timestamptz not null,
  generated_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  published_at timestamptz,
  unique (season_id, week_key)
);

create index if not exists weekly_recaps_publication_idx
  on public.weekly_recaps (
    season_id,
    published_at desc
  )
  where status = 'published';

alter table public.weekly_recaps
  enable row level security;

drop policy if exists public_read_published_weekly_recaps
  on public.weekly_recaps;

create policy public_read_published_weekly_recaps
  on public.weekly_recaps
  for select
  to anon, authenticated
  using (status = 'published');

revoke all on table public.weekly_recaps
  from public, anon, authenticated;

grant select on table public.weekly_recaps
  to anon, authenticated;

grant all on table public.weekly_recaps
  to service_role;

grant usage, select on sequence public.weekly_recaps_id_seq
  to service_role;

comment on table public.weekly_recaps is
  'Locked weekly recap facts with commissioner-editable text and publication status.';

comment on column public.weekly_recaps.recap_data is
  'Generated weekly winner, runner-up, standings movement, college-team performance, and final standings data.';

comment on column public.weekly_recaps.source_finalized_at is
  'Finalized weekly snapshot timestamp used to generate the locked recap facts.';
