create table if not exists public.wheel_entries (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.seasons(id)
    on delete cascade,
  item_text text not null
    check (char_length(btrim(item_text)) between 2 and 160),
  submitted_by uuid not null,
  submitted_by_owner_id bigint
    references public.owners(id)
    on delete set null,
  status text not null default 'pending'
    check (
      status in (
        'pending',
        'approved',
        'rejected',
        'selected'
      )
    ),
  created_at timestamptz not null default now(),
  approved_at timestamptz,
  rejected_at timestamptz,
  selected_at timestamptz,
  constraint wheel_entries_submitted_by_fkey
    foreign key (submitted_by)
    references public.user_profiles(user_id)
    on delete cascade
);

create table if not exists public.wheel_draws (
  id bigint generated by default as identity primary key,
  season_id bigint not null
    references public.seasons(id)
    on delete cascade,
  draw_key text not null,
  week_label text not null,
  selected_entry_id bigint not null
    references public.wheel_entries(id),
  selected_text text not null,
  entry_snapshot jsonb not null,
  drawn_at timestamptz not null default now(),
  unique (season_id, draw_key),
  check (jsonb_typeof(entry_snapshot) = 'array')
);

create table if not exists public.wheel_views (
  draw_id bigint not null
    references public.wheel_draws(id)
    on delete cascade,
  user_id uuid not null
    references public.user_profiles(user_id)
    on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (draw_id, user_id)
);

create index if not exists wheel_entries_season_status_idx
  on public.wheel_entries(
    season_id,
    status,
    approved_at
  );

create index if not exists wheel_entries_submitter_idx
  on public.wheel_entries(
    submitted_by,
    created_at desc
  );

create index if not exists wheel_draws_season_drawn_idx
  on public.wheel_draws(
    season_id,
    drawn_at desc
  );

create index if not exists wheel_entries_owner_idx
  on public.wheel_entries(
    submitted_by_owner_id
  );

create index if not exists wheel_views_user_idx
  on public.wheel_views(user_id);

alter table public.wheel_entries
  enable row level security;

alter table public.wheel_draws
  enable row level security;

alter table public.wheel_views
  enable row level security;

revoke all on table public.wheel_entries
  from public, anon, authenticated;

revoke all on table public.wheel_draws
  from public, anon, authenticated;

revoke all on table public.wheel_views
  from public, anon, authenticated;

grant all on table public.wheel_entries
  to service_role;

grant all on table public.wheel_draws
  to service_role;

grant all on table public.wheel_views
  to service_role;

revoke all on sequence public.wheel_entries_id_seq
  from public, anon, authenticated;

revoke all on sequence public.wheel_draws_id_seq
  from public, anon, authenticated;

grant usage, select
  on sequence public.wheel_entries_id_seq
  to service_role;

grant usage, select
  on sequence public.wheel_draws_id_seq
  to service_role;

create or replace function public.draw_weekly_wheel(
  p_season_id bigint,
  p_draw_key text,
  p_week_label text
)
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  existing_draw public.wheel_draws%rowtype;
  chosen_entry public.wheel_entries%rowtype;
  snapshot jsonb;
  new_draw public.wheel_draws%rowtype;
begin
  if p_season_id is null
    or nullif(btrim(p_draw_key), '') is null
    or nullif(btrim(p_week_label), '') is null
  then
    raise exception
      'season, draw key and week label are required';
  end if;

  perform pg_advisory_xact_lock(
    hashtextextended(
      'weekly-wheel:'
        || p_season_id::text
        || ':'
        || p_draw_key,
      0
    )
  );

  select *
  into existing_draw
  from public.wheel_draws
  where season_id = p_season_id
    and draw_key = p_draw_key;

  if found then
    return jsonb_build_object(
      'drawn', false,
      'reason', 'already_drawn',
      'drawId', existing_draw.id,
      'selectedEntryId',
        existing_draw.selected_entry_id
    );
  end if;

  select coalesce(
    jsonb_agg(
      jsonb_build_object(
        'id', id,
        'item_text', item_text
      )
      order by approved_at, id
    ),
    '[]'::jsonb
  )
  into snapshot
  from public.wheel_entries
  where season_id = p_season_id
    and status = 'approved';

  if jsonb_array_length(snapshot) = 0 then
    return jsonb_build_object(
      'drawn', false,
      'reason', 'no_approved_entries'
    );
  end if;

  select *
  into chosen_entry
  from public.wheel_entries
  where season_id = p_season_id
    and status = 'approved'
  order by random()
  limit 1
  for update;

  insert into public.wheel_draws (
    season_id,
    draw_key,
    week_label,
    selected_entry_id,
    selected_text,
    entry_snapshot
  )
  values (
    p_season_id,
    p_draw_key,
    btrim(p_week_label),
    chosen_entry.id,
    chosen_entry.item_text,
    snapshot
  )
  returning *
  into new_draw;

  update public.wheel_entries
  set
    status = 'selected',
    selected_at = new_draw.drawn_at
  where id = chosen_entry.id;

  return jsonb_build_object(
    'drawn', true,
    'drawId', new_draw.id,
    'selectedEntryId',
      new_draw.selected_entry_id,
    'selectedText',
      new_draw.selected_text,
    'entryCount',
      jsonb_array_length(snapshot)
  );
end;
$function$;

create or replace function
public.run_due_weekly_wheel_draw()
returns jsonb
language plpgsql
security definer
set search_path to 'public', 'pg_temp'
as $function$
declare
  eastern_now timestamp;
  draw_key text;
  week_label text;
begin
  eastern_now :=
    timezone('America/New_York', now());

  if extract(isodow from eastern_now) <> 6
    or extract(hour from eastern_now) <> 20
  then
    return jsonb_build_object(
      'drawn', false,
      'reason',
      'not_saturday_8pm_eastern'
    );
  end if;

  draw_key :=
    to_char(eastern_now, 'YYYY-MM-DD');

  week_label :=
    'Week of '
    || to_char(
      eastern_now,
      'Mon FMDD, YYYY'
    );

  if draw_key < '2026-09-05' then
    return jsonb_build_object(
      'drawn', false,
      'reason', 'before_launch'
    );
  end if;

  return public.draw_weekly_wheel(
    1,
    draw_key,
    week_label
  );
end;
$function$;

revoke all on function
  public.draw_weekly_wheel(
    bigint,
    text,
    text
  )
  from public, anon, authenticated;

revoke all on function
  public.run_due_weekly_wheel_draw()
  from public, anon, authenticated;

grant execute on function
  public.draw_weekly_wheel(
    bigint,
    text,
    text
  )
  to service_role;

grant execute on function
  public.run_due_weekly_wheel_draw()
  to service_role;

do $block$
declare
  old_job_id bigint;
begin
  select jobid
  into old_job_id
  from cron.job
  where jobname = 'cfb-weekly-wheel-draw';

  if old_job_id is not null then
    perform cron.unschedule(old_job_id);
  end if;
end;
$block$;

select cron.schedule(
  'cfb-weekly-wheel-draw',
  '0 * * * *',
  $cron$
    select public.run_due_weekly_wheel_draw();
  $cron$
);
